#!/usr/bin/env python3
"""Which Java classes read each pzopt.Config key, for the Optimizations tab's search box.

Config declares every key as `static final <type> NAME = bool|integer|string("key", ...)`; a class that reads the key
names `Config.NAME` (or `pzopt.Config.NAME`). This walks src/overrides and src/pzopt, collects the classes per key
and writes src/lua/client/pzopt/pzopt_optimizations_classes.lua (a global table key -> { "Class", ... }, the game's
overridden classes by simple name, ours as pzopt.Name). build.sh runs it before copying the Lua.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "src/pzopt/pzopt/Config.java"
OUT = ROOT / "src/lua/client/pzopt/pzopt_optimizations_classes.lua"

# aoStrength("key"): the per-surface AO strengths, an integer key that falls back on the old aoStrengthPct
DECL = re.compile(r'static\s+final\s+[\w<>\[\]]+\s+([A-Z][A-Z0-9_]*)\s*=.*?\b(?:bool|integer|string|aoStrength)\(\s*"(\w+)"')
LIVE_FIELD = re.compile(r'static\s+volatile\s+[\w<>\[\]]+\s+([A-Z][A-Z0-9_]*); // option key: (\w+)')


def main():
    fields = {}  # FIELD -> key
    for line in CONFIG.read_text().splitlines():
        m = DECL.search(line) or LIVE_FIELD.search(line)
        if m:
            fields[m.group(1)] = m.group(2)
    # Config's own static methods that read a key (effectiveWorkers() -> parallel, workers) count as reading it
    via = {}  # method -> {key}
    src = CONFIG.read_text()
    for m in re.finditer(r'static\s+[\w<>\[\]]+\s+(\w+)\s*\([^)]*\)\s*(?:throws[^{]*)?\{', src):
        depth, i = 1, m.end()
        while depth and i < len(src):
            depth += {"{": 1, "}": -1}.get(src[i], 0)
            i += 1
        body = src[m.end():i]
        keys = {k for f, k in fields.items() if re.search(r'\b%s\b' % f, body)}
        if 0 < len(keys) <= 4:  # describe() and other summaries name every key; they read nothing for a feature
            via.setdefault(m.group(1), set()).update(keys)
    ref = re.compile(r'\bConfig\.(' + "|".join(sorted(fields, key=len, reverse=True)) + r')\b')
    call = re.compile(r'\bConfig\.(' + "|".join(sorted(via, key=len, reverse=True)) + r')\s*\(') if via else None
    classes = {key: set() for key in fields.values()}
    for base, prefix in ((ROOT / "src/overrides", ""), (ROOT / "src/shims", ""), (ROOT / "src/pzopt", "pzopt.")):
        for path in sorted(base.rglob("*.java")):
            if path == CONFIG:
                continue
            name = prefix + path.stem
            text = path.read_text(errors="replace")
            for m in ref.finditer(text):
                classes[fields[m.group(1)]].add(name)
            for m in call.finditer(text) if call else ():
                for key in via[m.group(1)]:
                    classes[key].add(name)
    lines = [
        "-- Generated by scripts/option-classes.py (build.sh runs it): the Java classes that read each pzopt.Config key,",
        "-- for the Optimizations tab's search box. Do not edit by hand.",
        "PzoptOptionClasses = {",
    ]
    for key in sorted(classes, key=str.lower):
        names = sorted(classes[key], key=lambda n: (n.startswith("pzopt."), n.lower()))
        if names:
            lines.append("    %s = { %s }," % (key, ", ".join('"%s"' % n for n in names)))
    lines += ["}", "return PzoptOptionClasses", ""]
    text = "\n".join(lines)
    if not OUT.exists() or OUT.read_text() != text:
        OUT.write_text(text)
    empty = sorted(k for k, v in classes.items() if not v)
    print("option-classes: %d keys, %d with classes -> %s" % (len(classes), len(classes) - len(empty), OUT.relative_to(ROOT)))
    if "-v" in sys.argv and empty:
        print("  no reader outside Config: " + " ".join(empty))


if __name__ == "__main__":
    main()
